#!/usr/bin/env bash
# -*- mode: shell-script; -*-

which bxdevtools-config > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo >&2 "[error] Cannot found BxDevTools setup! Abort!"
    exit 1
fi

. $(bxdevtools-config --moduledir)/_bxdev_app.bash
. $(bxdevtools-config --moduledir)/_bxdev_message.bash
. $(bxdevtools-config --moduledir)/_bxdev_git.bash

function app_usage()
{
    cat <<EOF
Usage: bxgit_terminate_feature_branch [OPTION...] TOPIC

Known values for OPTION are:

 --help		display this help and exit.
 --debug	activate debug mode.
 --topic NAME   the topic of the new feature branch.
 --remote       the new feature branch is associated
                with an upstream remote origin.

EOF
    return 0
}

debug=false
to="develop"
topic=""
remote=false
feature_branch=""
feature_branch_label=""

while [ -n "$1" ]; do
    optarg="$1"
    if [ "x${optarg:0:1}" = "x-" ]; then
	option="${optarg}"
	if [ "${optarg}" = "--help" ]; then
	    app_usage
	    bxdev_app_exit 0
	elif [ "${optarg}" = "--debug" ]; then
	    debug=true
	elif [ "${optarg}" = "--topic" -o "${optarg}" = "-t" ]; then
	    shift 1
	    topic="$1"
	elif [ "${optarg}" = "--remote" ]; then
	    remote=true
	else
	    bxdev_app_exit 1 "Unsupported option '${option}'!"
	fi
    else
	argument="${optarg}"
	if [ -z "${feature_branch_label}" ]; then
	    bxdev_message_trace "Parsing feature branch label..."
	    feature_branch_label="${argument}"
	else
	    bxdev_app_exit 1 "Unsupported argument '${argument}'!"
	fi
    fi
    shift 1
done

bxdev_message_info "Feature branch label = '${feature_branch_label}'"

if [ -n "${feature_branch_label}" ]; then
    bxdev_message_info "Checking feature branch label..."
    fb="${feature_branch_label}"
    if [ "x${fb:0:9}" != "x_feature-" -a "x${fb:0:8}" != "xfeature-" ]; then
	feature_branch="feature-${fb}"
	if [ ${remote} == false ]; then
	    feature_branch="_feature-${fb}"
	fi
	topic="${fb}"
	bxdev_message_info "resolved feature branch = '${feature_branch}'"
	bxdev_message_info "resolved topic = '${topic}'"
    else
	feature_branch=${feature_branch_label}
    fi
fi
if [ -z "${feature_branch}" ]; then
    if [ -z "${topic}" ]; then
	app_usage
	bxdev_app_exit 1 "Missing feature branch topic!"
    else
	feature_branch="_feature-${topic}"
	if [ ${remote} == true ]; then
	    feature_branch="feature-${topic}"
	fi
    fi
fi
bxdev_message_info "Feature branch name = '${feature_branch}'"

if [ -z "${topic}" ]; then
    if [ "x${feature_branch:0:9}" = "x_feature-" ]; then
	remote=true
	topic="${feature_branch:9}"
    elif [ "x${feature_branch:0:9}" = "xfeature-" ]; then
	remote=false
	topic="${feature_branch:8}"
    fi
fi

if [ ${debug} = true ]; then
    bxdev_message_debug "topic          = '${topic}'"
    bxdev_message_debug "remote         = ${remote}"
    bxdev_message_debug "feature_branch = '${feature_branch}'"
    bxdev_message_debug "from branch    = '${from}'"
fi

bxdev_git_check_repository
if [ $? -ne 0 ]; then
    bxdev_app_exit 1 "Not a base Git repository!"
else
    bxdev_message_info "Found a base Git repository."
fi

bxdev_git_local_branch_exists "${feature_branch}"
if [ $? -ne 0 ]; then
    bxdev_app_exit 1 "No local '${feature_branch}' feature branch exists in this Git repository!"
else
    bxdev_message_info "Found a local '${feature_branch}' feature branch."
fi

bxdev_git_local_branch_exists "${to}"
if [ $? -ne 0 ]; then
    bxdev_app_exit 1 "No '${to}' branch exists in this Git repository!"
else
    bxdev_message_info "Found a local '${to}' branch."
fi

cbn=$(bxdev_git_current_branch_name)
bxdev_message_info "Current branch name: '${bxdev_git_current_branch_name}'"
if [ "${cbn}" != "${feature_branch}" ]; then
    bxdev_app_exit 1 "The '$feature_branch}' branch is not the active one!"
fi

git checkout ${to}
if [ $? -ne 0 ]; then
    bxdev_app_exit 1 "Could not switch to local '${to}' branch!"
fi

bxdev_git_local_branch_exists "${feature_branch}"
if [ $? -ne 0 ]; then
    bxdev_app_exit 1 "No local '${feature_branch}' feature branch exists in this Git repository!"
else
    bxdev_message_info "Found a local '${feature_branch}' feature branch."
fi

bxdev_message_info "Merge '${feature_branch}' feature branch into '${to}' branch..."
git merge -m "Merge feature branch '${feature_branch}' into branch '${to}'" --no-ff ${feature_branch}
if [ $? -ne 0 ]; then
    bxdev_app_exit 1 "Could not merge local '${feature_branch}' feature branch into '${to}' branch!"
fi

bxdev_message_info "Deleting local '${feature_branch}' feature branch..."
git branch -d ${feature_branch}
if [ $? -ne 0 ]; then
    bxdev_app_exit 1 "Could not delete local '${feature_branch}' feature branch!"
fi

bxdev_app_exit 1 "Abort"
# if [ ${remote} == true ]; then
#     bxdev_message_info "Pushing modifications from local '${to}' branch to 'origin/${to}' branch..."
#     git push origin ${to}
#     if [ $? -ne 0 ]; then
# 	bxdev_app_exit 1 "Could not push modifications from local '${to}' branch to 'origin/${to}' branch!"
#     fi
# fi

bxdev_app_exit 0

# end
